export const UseractionType = {
  SEND_OTP: "SEND_OTP",
  SEND_OTP_START: "SEND_OTP_START",
  SEND_OTP_FINISHED: "SEND_OTP_FINISHED",
  SEND_OTP_ERROR: "SEND_OTP_ERROR",

  LOGIN: "LOGIN",
  LOGIN_START: "LOGIN_START",
  LOGIN_FINISHED: "LOGIN_FINISHED",
  LOGIN_ERROR: "LOGIN_ERROR",

  USER_SET: "USER_SET",
  LOGIN_RESET: "LOGIN_RESET",
  SET_USER_AND_TOKEN: "SET_USER_AND_TOKEN",
};
